src/Kerbero.Common/Entities/NukiAccount.cs, src/Kerbero.Common/Exceptions/AccountNotTrackedException.cs, src/Kerbero.Common/Exceptions/InvalidTokenException.cs, src/Kerbero.Common/Exceptions/TokenExpiredException.cs, src/Kerbero.Common/Interactors/CreateNukiAccountInteractor.cs, src/Kerbero.Common/Interfaces/InteractorInterface.cs, src/Kerbero.Common/Kerbero.Common.csproj, src/Kerbero.Common/Models/AccountMapper/NukiAccountMapper.cs, src/Kerbero.Common/Models/NukiAccountExternalRequestDto.cs, src/Kerbero.Common/Models/NukiAccountExternalResponseDto.cs, src/Kerbero.Common/Models/NukiAccountPresentationDto.cs, src/Kerbero.Common/Repositories/INukiExternalAuthenticationRepository.cs, src/Kerbero.Common/Repositories/INukiPersistentAccountRepository.cs, src/Kerbero.Infrastructure/Clients/NukiExternalAuthenticationRepository.cs, src/Kerbero.Infrastructure/Kerbero.Infrastructure.csproj, src/Kerbero.Infrastructure/Options/NukiExternalOptions.cs, tests/Kerbero.Common.Tests/Interactors/CreateNukiAccountInteractorTests.cs, tests/Kerbero.Infrastructure.Tests/Clients/NukiHttpClientTests.cs
- Created entities, models, exceptions and interfaces for an interactor which create a Nuki account entity.
=> Implemented interactor that creates a SmartLock provider entity

src/Kerbero.Common/Errors/CreateNukiAccountErrors/DuplicateEntryError.cs, src/Kerbero.Common/Errors/CreateNukiAccountErrors/PersistentResourceNotAvailableError.cs, src/Kerbero.Common/Errors/CreateNukiAccountErrors/ResourceConnectionError.cs, src/Kerbero.Infrastructure/ConfigureService.cs, src/Kerbero.Infrastructure/Context/ApplicationDbContext.cs, src/Kerbero.Infrastructure/Interfaces/IApplicationDbContext.cs, src/Kerbero.Infrastructure/Kerbero.Infrastructure.csproj, src/Kerbero.Infrastructure/Repositories/NukiExternalAuthenticationRepository.cs, src/Kerbero.Infrastructure/Repositories/NukiPersistentAccountRepository.cs, src/Kerbero.WebApi/Exceptions/DevException.cs, src/Kerbero.WebApi/Models/ErrorMapper/HttpResponseExceptionMap.cs, src/Kerbero.WebApi/Models/KerberoWebApiErrorResponse.cs, src/Kerbero.WebApi/Program.cs, tests/Kerbero.Common.Tests/Interactors/CreateNukiAccountInteractorTests.cs, tests/Kerbero.Infrastructure.Tests/Kerbero.Infrastructure.Tests.csproj, tests/Kerbero.Infrastructure.Tests/Repositories/NukiExternalAuthenticationRepositoryTests.cs, tests/Kerbero.Infrastructure.Tests/Repositories/NukiPersistentAccountRepositoryTest.cs, tests/Kerbero.WebApi.Tests/NukiAuthenticationControllerTest.cs
- Nuki account persistent repository (with add and saveChangesAsync and drafted error management)
- Created and tested db context
=> Implemented Nuki account persistent repository and db context

Kerbero.sln, src/Kerbero.Infrastructure/ConfigureService.cs, src/Kerbero.Infrastructure/Context/ApplicationDbContext.cs, src/Kerbero.Infrastructure/Interfaces/IApplicationDbContext.cs, src/Kerbero.Infrastructure/Kerbero.Infrastructure.csproj, src/Kerbero.Infrastructure/Options/NukiExternalOptions.cs, src/Kerbero.Infrastructure/Repositories/NukiExternalAuthenticationRepository.cs, src/Kerbero.WebApi/Controllers/NukiAuthenticationController.cs, src/Kerbero.WebApi/Kerbero.WebApi.csproj, src/Kerbero.WebApi/Models/CustomActionResults/KerberoErrorActionResult.cs, src/Kerbero.WebApi/Models/KerberoWebApiErrorResponse.cs, src/Kerbero.WebApi/Program.cs, src/Kerbero.WebApi/appsettings.Development.json, src/Kerbero.WebApi/appsettings.Test.json, tests/Kerbero.Infrastructure.Tests/Repositories/NukiExternalAuthenticationRepositoryTests.cs, tests/Kerbero.Integration.Tests/Kerbero.Integration.Tests.csproj, tests/Kerbero.Integration.Tests/NukiAuthenticationIntegrationTests.cs, tests/Kerbero.Integration.Tests/Usings.cs, tests/Kerbero.WebApi.Tests/NukiAuthenticationControllerTest.cs
- Written integration tests
- Configured services and application DI
- Options pattern for db
- Fix response management of web API
=> Integration tests for Nuki authentication

src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockExternalRepository.cs, tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockExternalRepositoryTests.cs
- implemented external repository, which calls nuki API to retrieve a smartlock
- related tests
=> feat: external repository to create smartlock

src/Kerbero.Domain/NukiActions/Entities/NukiSmartLock.cs, src/Kerbero.Domain/NukiActions/Entities/NukiSmartLockState.cs, src/Kerbero.Domain/NukiAuthentication/Entities/NukiAccount.cs, src/Kerbero.Infrastructure/Common/Context/ApplicationDbContext.cs, src/Kerbero.Infrastructure/Common/Interfaces/IApplicationDbContext.cs, src/Kerbero.Infrastructure/NukiActions/Configurations/NukiSmartLockStateTypeConfiguration.cs, src/Kerbero.Infrastructure/NukiActions/Configurations/NukiSmartLockTypeConfiguration.cs, src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockPersistentRepository.cs, tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockPersistentRepositoryTests.cs, tests/Kerbero.Infrastructure.Tests/NukiAuthentication/Repositories/NukiAccountPersistentRepositoryTest.cs
- persistent repo, which creates a SmartLock entity and upload it inside db
- related tests
=> feat: persistent create smartlock

src/Kerbero.Domain/NukiActions/Interactors/CloseNukiSmartLockInteractor.cs, src/Kerbero.Domain/NukiActions/Interactors/OpenNukiSmartLockInteractor.cs, src/Kerbero.Domain/NukiActions/Repositories/INukiSmartLockPersistentRepository.cs, src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockPersistentRepository.cs, src/Kerbero.Infrastructure/NukiAuthentication/Repositories/NukiAccountPersistentRepository.cs, tests/Kerbero.Domain.Tests/Interactors/NukiActions/OpenNukiSmartLockInteractorTests.cs, tests/Kerbero.Domain.Tests/NukiActions/Interactors/CloseNukiSmartLockInteractorTest.cs, tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockPersistentRepositoryTests.cs
- persistent repo to `GetById` a smartlock from db 
- async GetById refactor
- refactor exceptions
Fix #41
=> feat: persistent open smartlock

src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockExternalRepository.cs, tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockExternalRepositoryTests.cs
=> feat: external repository to close smartlock

src/Kerbero.Domain/NukiActions/Mappers/NukiSmartLockMapper.cs, src/Kerbero.Domain/NukiActions/Models/PresentationResponse/KerberoSmartLockPresentationResponse.cs, src/Kerbero.Domain/NukiAuthentication/Interactors/AuthenticateNukiAccountInteractor.cs, src/Kerbero.Infrastructure/NukiAuthentication/Repositories/NukiAccountPersistentRepository.cs, tests/Kerbero.Domain.Tests/NukiActions/Interactors/GetNukiSmartLocksListInteractorTest.cs, tests/Kerbero.Domain.Tests/NukiAuthentication/Interactors/GetNukiAccountInteractorTests.cs, tests/Kerbero.Infrastructure.Tests/NukiAuthentication/Repositories/NukiAccountPersistentRepositoryTest.cs, tests/Kerbero.Integration.Tests/NukiCreateSmartLockIntegrationTests.cs, tests/Kerbero.Integration.Tests/NukiSmartLocksListIntegrationTests.cs, tests/Kerbero.WebApi.Tests/ModelStateDictionaryExtensionsTest.cs, tests/Kerbero.WebApi.Tests/NukiSmartLockControllerTests.cs
Fix #44 
- Remove ExternalAccountId reference (useless)
- Add AccountId reference to internal entity
- Fix data mapping
- Fix update NukiAccount logico
- Fix refresh token
=> feat: integration test for creating nuki smartlock

src/Kerbero.Domain/NukiActions/Errors/SmartLockNotReachableError.cs, src/Kerbero.Infrastructure/ConfigureService.cs, src/Kerbero.WebApi/ConfigureService.cs, src/Kerbero.WebApi/Controllers/NukiSmartLockController.cs, src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs, tests/Kerbero.WebApi.Tests/NukiSmartLockControllerTests.cs
Fix #46 
- added SmartLockNotReachable error
- added methods to controller
- added tests for controller
=> feat: controller to open smartlock

src/Kerbero.WebApi/ConfigureService.cs, src/Kerbero.WebApi/Controllers/NukiSmartLockController.cs, tests/Kerbero.Integration.Tests/NukiCreateSmartLockIntegrationTests.cs, tests/Kerbero.WebApi.Tests/NukiSmartLockControllerTests.cs
Fix #51
- added controller
- added tests
- add interactor to configuration
=> feat: controller to close smartlock

src/Kerbero.Infrastructure/Migrations/20221110093033_InitialCreate.Designer.cs, src/Kerbero.Infrastructure/Migrations/20221110093033_InitialCreate.cs, src/Kerbero.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
=> Migrations for identity

src/Kerbero.Domain/NukiAuthentication/Errors/NukiAccountNotFoundError.cs, src/Kerbero.Domain/NukiAuthentication/Interactors/AuthenticateNukiAccountInteractor.cs, src/Kerbero.Domain/NukiAuthentication/Repositories/INukiAccountPersistentRepository.cs, src/Kerbero.Infrastructure/NukiAuthentication/Repositories/NukiAccountPersistentRepository.cs, tests/Kerbero.Domain.Tests/NukiAuthentication/Interactors/GetNukiAccountInteractorTests.cs, tests/Kerbero.Infrastructure.Tests/NukiAuthentication/Repositories/NukiAccountPersistentRepositoryTest.cs
=> FindAsync in NukiAccountPersistentRepository.cs

src/Kerbero.WebApi/Controllers/NukiSmartLockController.cs, src/Kerbero.WebApi/Models/Requests/CloseNukiSmartLockRequest.cs, src/Kerbero.WebApi/Models/Requests/CreateNukiSmartLockRequest.cs, src/Kerbero.WebApi/Models/Requests/OpenNukiSmartLockRequest.cs, tests/Kerbero.Integration.Tests/NukiCloseSmartLockIntegrationTests.cs, tests/Kerbero.Integration.Tests/NukiCreateSmartLockIntegrationTests.cs, tests/Kerbero.Integration.Tests/NukiOpenSmartLockIntegrationTests.cs, tests/Kerbero.Integration.Tests/NukiSmartLocksListIntegrationTests.cs, tests/Kerbero.WebApi.Tests/NukiSmartLockControllerTests.cs
Fix #61
Integration tests with minor fixes.
=> Integration test for opening and closing a smartlock and minor fix

web-app/package-lock.json, web-app/package.json
=> Added husky dependency to package.json

web-api/src/Kerbero.Identity.Library/Modules/Authentication/Dtos/AuthenticatedDto.cs, web-api/src/Kerbero.Identity.Library/Modules/Authentication/Dtos/LoginDto.cs, web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs, web-api/src/Kerbero.Identity/Modules/Authentication/Controllers/AuthenticationController.cs, web-api/src/Kerbero.Identity/Modules/Authentication/Models/AuthenticatedModel.cs, web-api/src/Kerbero.Identity/Modules/Authentication/Services/AuthenticationService.cs, web-api/src/Kerbero.Identity/Modules/Authentication/Services/IAuthenticationService.cs, web-api/src/Kerbero.Infrastructure/Common/Context/ApplicationDbContext.cs, web-api/src/Kerbero.Infrastructure/Kerbero.Infrastructure.csproj, web-api/src/Kerbero.WebApi/Program.cs, web-api/tests/Kerbero.Identity.Tests/Modules/Authentication/AuthenticationServiceTest.cs
- Db integration
- Adjusted controller method for cookie
- Adjusted test
Fix #65 #83
=> Identity integration

web-api/src/Kerbero.Identity/Modules/Authentication/Controllers/AuthenticationController.cs, web-api/src/Kerbero.Identity/Modules/Authentication/Services/AuthenticationManager.cs, web-api/src/Kerbero.Identity/Modules/Authentication/Services/AuthenticationService.cs, web-api/src/Kerbero.Identity/Modules/Authentication/Services/IAuthenticationManager.cs, web-api/src/Kerbero.Identity/Modules/Authentication/Services/IAuthenticationService.cs, web-api/tests/Kerbero.Identity.Tests/Modules/Authentication/AuthenticationServiceTest.cs
=> Logout identity library controller

web-api/src/Kerbero.Identity/Modules/Users/Controllers/UsersController.cs, web-api/src/Kerbero.Identity/Modules/Users/Services/IUserManager.cs, web-api/src/Kerbero.Identity/Modules/Users/Services/IUserService.cs, web-api/src/Kerbero.Identity/Modules/Users/Services/UserManager.cs, web-api/src/Kerbero.Identity/Modules/Users/Services/UserService.cs, web-api/tests/Kerbero.Identity.Tests/Modules/Users/Services/UserServiceTest.cs
=> Registration confirm callback endpoint

web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs, web-api/src/Kerbero.Identity/Modules/Authentication/Services/AuthenticationService.cs, web-api/tests/Kerbero.Identity.Tests/Modules/Authentication/AuthenticationServiceTest.cs
=> Check email confirmation during login

web-api/src/Kerbero.Identity/Common/KuamaIdentityConfiguration.cs, web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs, web-api/src/Kerbero.Identity/Kerbero.Identity.csproj, web-api/src/Kerbero.Identity/Modules/Email/Options/EmailSenderServiceOptions.cs, web-api/src/Kerbero.Identity/Modules/Email/Services/EmailSenderService.cs, web-api/src/Kerbero.Identity/Modules/Email/Services/IEmailSenderService.cs, web-api/src/Kerbero.WebApi/Program.cs, web-api/src/Kerbero.WebApi/appsettings.Development.json, web-api/tests/Kerbero.Identity.Tests/Modules/Email/Services/EmailServiceTest.cs
=> Email sender with SendGrid client

web-app/.gitignore, web-app/cypress.config.ts, web-app/cypress/e2e/silly.cy.tsx, web-app/cypress/support/auth-routing.cy.ts, web-app/cypress/support/component-index.html, web-app/cypress/support/cypress.d.ts, web-app/cypress/support/e2e.ts, web-app/cypress/tsconfig.json, web-app/package-lock.json, web-app/package.json, web-app/src/App.vue, web-app/src/auth/auth.store.ts, web-app/src/auth/log-in.component.vue, web-app/src/dashboard/dashboard.component.vue, web-app/src/main.ts, web-app/src/routing/router.ts, web-app/src/routing/routing-guards.ts, web-app/src/routing/routing-helpers.ts, web-app/test/auth/auth.store.test.ts
Just introducing basic routing features:
- do not allow to see login page to logged user
- redirect to login a not logged user that tries to access any route != login
Also:
- fix cypress setup
- introduce component tests with cypress
- basic unit tests for `authStore`
=> feat: mvp routing / auth store

.github/workflows/webapp-integration.yml, web-app/package-lock.json, web-app/vitest.config.ts
This is introducing coverage report, but sadly the report does not take in account the e2e tests
=> feat: add web-app coverage report

web-api/src/Kerbero.Domain/SmartLockKeys/Entities/SmartLockKey.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Errors/UnableToGenerateKeyError.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Managers/ISmartLockKeyGeneratorManager.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Mappers/SmartLockKeyMapper.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Models/PresentationRequests/CreateSmartLockKeyPresentationRequest.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Models/PresentationResponses/CreateSmartLockKeyPresentationResponse.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Repositories/ISmartLockKeyPersistentRepository.cs, web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/CreateSmartLockKeyInteractorTest.cs
- Created entity
- Created interactor
- New Errors key-related
- Tests
Closes #70, closes #69
=> CreateKey interactor

.github/workflows/webapi-integration.yml, README.md, web-api/README.md, web-api/global.json, web-api/src/Kerbero.Domain/Kerbero.Domain.csproj, web-api/src/Kerbero.Identity.Library/Kerbero.Identity.Library.csproj, web-api/src/Kerbero.Identity/Kerbero.Identity.csproj, web-api/src/Kerbero.Infrastructure/Kerbero.Infrastructure.csproj, web-api/src/Kerbero.WebApi/Kerbero.WebApi.csproj, web-api/tests/Kerbero.Common.Data.Tests/Kerbero.Common.Data.Tests.csproj, web-api/tests/Kerbero.Domain.Tests/Kerbero.Domain.Tests.csproj, web-api/tests/Kerbero.Identity.Tests/Kerbero.Identity.Tests.csproj, web-api/tests/Kerbero.Infrastructure.Tests/Kerbero.Infrastructure.Tests.csproj, web-api/tests/Kerbero.Integration.Tests/Kerbero.Integration.Tests.csproj, web-api/tests/Kerbero.WebApi.Tests/Kerbero.WebApi.Tests.csproj
- .Net7 porting
- Packages update in csproj
=> .NET7 porting

web-api/src/Kerbero.Domain/NukiCredentials/Errors/NukiCredentialInvalidTokenError.cs, web-api/src/Kerbero.Domain/NukiCredentials/Interactors/CreateNukiCredentialInteractor.cs, web-api/src/Kerbero.Domain/NukiCredentials/Repositories/INukiCredentialRepository.cs, web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs, web-api/src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs, web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/CreateNukiCredentialInteractorTests.cs, web-api/tests/Kerbero.Infrastructure.Tests/NukiCredentials/Repositories/NukiCredentialRepositoryTests.cs, web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
=> feat: ensure provided token is valid against nuki api

web-api/src/Kerbero.Domain/NukiCredentials/Dtos/NukiCredentialDto.cs, web-api/src/Kerbero.Domain/NukiCredentials/Models/NukiCredentialModel.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractor.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/ICloseSmartLockWithKeyInteractor.cs, web-api/src/Kerbero.WebApi/Models/Requests/CloseSmartLockWithKeyRequest.cs, web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractorTests.cs
Coded interactor for closing a smart-lock with a smart-lock key
=> Close smart-lock with key interactor

web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs, web-api/src/Kerbero.WebApi/Mappers/NukiCredentialMapper.cs
- Now we should be able to get a list of nuki credentials
- No "abstraction" from nuki available
=> Get all nuki credentials associated with the kerbero account

web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractor.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/OpenSmartLockWithKeyInteractor.cs, web-api/src/Kerbero.Domain/SmartLockKeys/Models/SmartLockKeyModel.cs, web-api/src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs, web-api/tests/Kerbero.Integration.Tests/IntegrationTestsUtils.cs, web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/OpenSmartLockWithKeyIntegrationTests.cs
=> feat: validate keys based on date range

web-api/src/Kerbero.Domain/NukiCredentials/Interactors/DeleteNukiCredentialInteractor.cs, web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IDeleteNukiCredentialInteractor.cs, web-api/src/Kerbero.Domain/NukiCredentials/Repositories/INukiCredentialRepository.cs, web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs, web-api/src/Kerbero.WebApi/ConfigureService.cs, web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs, web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
=> Delete credentials by id (only for nuki)

web-api/src/Kerbero.Infrastructure/Common/Helpers/NukiRestApiClient.cs, web-api/src/Kerbero.Infrastructure/SmartLocks/Repositories/NukiSmartLockRepository.cs, web-api/tests/Kerbero.Infrastructure.Tests/SmartLocks/Repositories/NukiSmartLockRepositoryTests.cs
- Moved apiToken nullability check to NukiSmartLockRepository.cs
- Removed unused configurator in NukiSmartLockRepository.cs
=> Moved apiToken nullability check to repository

web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractor.cs, web-api/src/Kerbero.WebApi/ConfigureService.cs, web-api/src/Kerbero.WebApi/Controllers/SmartLockKeysController.cs, web-api/src/Kerbero.WebApi/Dtos/SmartLockKeys/CloseSmartLockWithKeyRequestDto.cs, web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/CloseSmartLockWithKeyIntegrationTests.cs
=> Added endpoint for closing smart-lock with key

web-app/src/auth/api/auth-actions.ts, web-app/src/auth/api/auth.schemas.ts, web-app/src/nuki-credentials/api/nuki-credential.schemas.ts, web-app/src/shared/http-client/http-client.ts, web-app/src/shared/smart-lock-provider.schemas.ts, web-app/src/smart-lock-keys/api/smart-lock-key-actions.ts, web-app/src/smart-lock-keys/api/smart-lock-key.schemas.ts
- direct export of the schemas.
=> Removed ParseOrThrow functions from auth.schema

web-app/src/nuki-credentials/api/nuki-credential-actions.ts, web-app/src/nuki-credentials/api/nuki-credential.schemas.ts, web-app/src/shared/http-client/http-client.ts
=> Create/delete nuki-credential api calls

web-app/src/smart-lock-keys/api/smart-lock-key-actions.ts, web-app/src/smart-lock-keys/api/smart-lock-key.schemas.ts
=> Open/close/update/delete smart-lock-key api calls

web-app/src/smart-locks/api/smart-lock.schemas.ts, web-app/src/smart-locks/components/smart-lock-list-item.component.vue, web-app/src/smart-locks/components/smart-lock-list.component.vue
=> Smart lock list component

web-app/src/shared/components/create-new-one-button.component.vue
=> Add credential button component

web-app/src/shared/components/datetime-widget.component.vue
=> feat: datetime-widget-component

web-app/package-lock.json, web-app/package.json, web-app/src/shared/components/datetime-widget.component.vue, web-app/src/shared/utils/date-time-formatter.ts, web-app/src/smart-lock-keys/components/date-time-display.component.vue, web-app/src/smart-lock-keys/components/date-time-manager.component.vue, web-app/src/smart-lock-keys/components/date-time-picker.component.vue
- date-time-manager control the under subcomponents
- date-time-picker (custom-picker from vue3-datepicker)
- date-time-display
=> Datetime component with picker and display for smart-lock-key

web-app/src/smart-lock-keys/api/smart-lock-key.schemas.ts, web-app/src/smart-lock-keys/components/date-time-display.component.vue, web-app/src/smart-lock-keys/components/date-time-manager.component.vue, web-app/src/smart-lock-keys/components/date-time-picker.component.vue, web-app/src/smart-lock-keys/components/smart-lock-keys-item.component.vue
=> Smart lock key component

web-app/src/smart-lock-keys/components/date-time-manager.component.vue, web-app/src/smart-lock-keys/components/smart-lock-keys-item.component.vue, web-app/src/smart-lock-keys/components/smart-lock-keys-list.component.vue
=> Smart lock keys list component

web-app/src/dashboard/pages/dashboard-page.component.vue, web-app/src/routing/router.ts, web-app/src/user-credentials/api/nuki-credential-actions.ts, web-app/src/user-credentials/components/select-provider.component.vue, web-app/src/user-credentials/pages/create-new-provider.page.vue, web-app/vite.config.ts
=> Create "create provider page"

web-app/src/routing/router.ts, web-app/src/shared/components/sync-loader.component.vue, web-app/src/smart-locks/api/smart-lock-actions.ts, web-app/src/smart-locks/components/smart-lock-list-item.component.vue, web-app/src/smart-locks/components/smart-lock-list.component.vue, web-app/src/smart-locks/pages/smart-locks.page.vue, web-app/vitest.config.ts
=> feat: /smart-locks page
